### ISSUE TITLE
How to I build it to use on Linux without android SDK ?

### ISSUE THREAD

**Issue by kk00ss** [couchbaselabs/cbforest-java#11]
Please help

**Comment by hideki** [comment]
To run the Couchbase Lite on Linux.
please use https://github.com/couchbase/couchbase-lite-java

**Comment by hideki** [comment]
If you have further question, please let us know.

**Comment by kk00ss** [comment]
Thanks for quick response,
 but Is Couchbase Lite  based on ForestDB ?
I"m trying to build this project with command ./gradlew -Pspec=java assemble --info 
and getting exception: ./gradlew -Pspec=java assemble --info

**Comment by kk00ss** [comment]
Thanks for quick response.

**Comment by hideki** [comment]
couchbase-lite-java-forestdb is submodule of couchbase-lite-java.
`./gradlew assemble` at home directory of couchbase-lite-java compiles forestdb too.

What platform are you using?

**Comment by kk00ss** [comment]
I'm using Ubuntu linux. I'm running `./gradlew assemble` yields build error related to SQCipher . I've openJDK on my system, I think it doesn't play well with "Oracle Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files." However I see that ":libraries:couchbase-lite-java-sqlcipher:compileLinux_amd64CouchbaseLiteJavaSQLCipherSharedLibraryCouchbaseLiteJavaSQLCipherCpp " was built succesfully and it's x86 counterpart fails to build - so I assume the problem is with cross-platform build and I need to install gcc/g++-multilib packages. I just thought it's not mandatory.
It would be great if jar files where available on maven :-) 
UPD: I've managed to build it - problem was with multilib packages.

**Comment by hideki** [comment]
- For SQLCipher on non-Android java platform, "Oracle Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files." is required for runtime. 
- I believe gcc/++-mulatilib packages are not required for non-cross compiling. We will look into this

> It would be great if jar files where available on maven :-) 
> We are working with build engineer for this.

Thank you very much for all your inputs!
