### ISSUE TITLE
ForestDB uses colons in its filenames

### ISSUE THREAD

**Issue by Poundex** [couchbaselabs/cbforest-java#66]
Most external SD Cards in the wild are FAT32 formatted, and FAT32 doesn't allow colons in filenames. 

This causes Database::getView to return null, and it logs 'Failed to registerView'

**Comment by hideki** [comment]
I believe this ticket is duplicated with https://github.com/couchbase/couchbase-lite-android/issues/837. And fix is already in master branch.
