### ISSUE TITLE
jackson annotation jar version problem

### ISSUE THREAD

**Issue by vvasuki** [couchbaselabs/cbforest-java#95]
Hi @hideki,

While executing this code (full [listing here](https://github.com/sanskrit-coders/subhAShita-db-sanskrit/blob/master/src/subhAShitaDb/QuoteInfoDb.scala)):
```
    dbManager =  new Manager(new JavaContext("data") {
      override def getRootDirectory: File = {
        val rootDirectoryPath = "/home/vvasuki/subhAShita-db-sanskrit"
        new File(rootDirectoryPath)
      }
    }, Manager.DEFAULT_OPTIONS)

```
I now get:
```
Exception in thread "main" java.lang.NoSuchFieldError: USE_DEFAULTS
	at com.fasterxml.jackson.annotation.JsonInclude$Value.<clinit>(JsonInclude.java:204)
	at com.fasterxml.jackson.databind.cfg.MapperConfig.<clinit>(MapperConfig.java:44)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:558)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:474)
	at com.couchbase.lite.Manager.<clinit>(Manager.java:75)
	at subhAShitaDb.QuoteInfoDb.openDatabasesLaptop(QuoteInfoDb.scala:23)
	at subhAShitaDb.dbMakerSanskrit$.main(QuoteInfoDb.scala:180)
	at subhAShitaDb.dbMakerSanskrit.main(QuoteInfoDb.scala)
```
The maven libraries I'm using are:
```
    <orderEntry type="library" name="Maven: org.slf4j:slf4j-api:1.6.1" level="project" />
    <orderEntry type="library" name="Maven: ch.qos.logback:logback-core:0.9.29" level="project" />
    <orderEntry type="library" name="Maven: ch.qos.logback:logback-classic:0.9.29" level="project" />
    <orderEntry type="library" name="org.apache.commons:commons-csv:1.4" level="project" />
    <orderEntry type="library" name="Maven: com.thoughtworks.paranamer:paranamer:2.7" level="project" />
    <orderEntry type="library" name="org.json4s:json4s_2.11:3.2.11" level="project" />
    <orderEntry type="library" name="org.json4s:json4s-native_2.11:3.5.1" level="project" />
    <orderEntry type="library" name="com.couchbase.lite:couchbase-lite-java:1.4.0" level="project" />
    <orderEntry type="library" name="com.couchbase.lite:couchbase-lite-java-forestdb:1.4.0" level="project" />

```

(Strangely, I was not getting this error yesterday..) Searching online, this [seems](http://stackoverflow.com/questions/36982173/java-lang-nosuchfielderror-use-defaults-thrown-while-validating-json-schema-thr) to be because the jackson annotations jar in the forestdb jar being too old (2.5). I got the same result with the 1.3.1 forestdb jar. Could you please take a look?

**Comment by hideki** [comment]
Hi @vvasuki,

Currently, CBL depends on Jackson `2.5.0`.
https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.3.1/build.gradle

How do you solve these dependencies? If you solve this by Maven or Gradle, Maven or Gradle should download only 2.5.0. I guess your environment has 2.6 or higher for some of Jackson jar files.  Please make sure what version of Jackson you are using.

**Comment by vvasuki** [comment]
Ah, thanks! 🙏 I rechecked and found that a module I was building on depended on org.json4s:json4s-jackson_2.11:3.5.1 . Removing it solves the problem (I suppose I should find a lower version of that package to use).

**Comment by hideki** [comment]
FYI: We might need to upgrade Jackson's version to the latest.

**Comment by hideki** [comment]
`2.8.6` is latest now. https://github.com/FasterXML/jackson
